### ISSUE TITLE
Problem in thread_blur

### ISSUE THREAD

**Issue by gnitnaw** [kevinbird61/Image-Processing#13]
In this function, in each loop
- You first read 25 pixels in global_src
- and you modified one pixel in global_src

However, you use this function to do multi-threading.

For example, if there are 3 threads.
thread 1 modifies pixel 1
thread 2 modifies pixel 2
thread 3 modifies pixel 3

All thread1,2,3 need to read pixels 1,2,3 (because they are neighbours).

Don't you think the output will depend on the sort of these 3 threads?
i.e.: race condition.

**Comment by kevinbird61** [comment]
Because I think the workload, which is equal to width(or height) / threads_count , will let each threads start at their first place and run to the end( where border on neighbor's area , and that part have been done by the following thread .)
Or you mean when the workload is small enough to let this situation happen?

**Comment by gnitnaw** [comment]
Let's observe like this, assume you distribute your pixels to 3 threads :

AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAA
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
BBBBBBBBBBBBBBBBBB
CCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCC
CCCCCCCCCCCCCCCC

A: Treat/modify by thead A
B: Treat/modify by thead B
C: Treat/modify by thead C

So thread B will need the data of all B and 4th+5th line of A(for the first row of B) and 1st+2nd line of C (for the last row of B).
Do you think part of B will have the same result when A/C is done before or not?

If you assume that all threads will start at the same time and their durations are similar (and the thread you create first MAY NOT be executed first).
It means, when thread B treats last row of B, it will use the data of "modified B and modified C".
However, the beginning of thread C will treat "original B and original C".

Understand what I mean?
Your result will be different if the number of threads and their sort are changed.

In order to avoid race condition, you should always calculate with original data.

**Comment by kevinbird61** [comment]
Thanks ! I'll think another way to modify them.
