### ISSUE TITLE
Unroll (don't use it anymore until 24h before your deadline, it's hard to read!) and others

### ISSUE THREAD

**Issue by gnitnaw** [kevinbird61/Image-Processing#14]
Please be careful when you are doing calculation among different type of variables. For example:

This is WRONG
unsigned int sum = 2000000000 + 2000000000;  // compiler will treat it as : unsigned int sum = (int)2000000000 + (int)2000000000; You will get overflow.
unsigned int sum = (unsigned int) (2000000000 + 2000000000); // compiler will treat it as : unsigned int sum = (unsigned int)((int)2000000000 + (int)2000000000); You will get overflow.

This is CORRECT
unsigned int sum = 2000000000u + 2000000000u;
unsigned int sum = (unsigned int) 2000000000 + 2000000000;

Now go to check your gaussian.c and fix such kind of problem. A lot!!

**Comment by kevinbird61** [comment]
Thanks for your reminder!
But int (unsigned int) size is 2 ~ 4 bytes , we take 4 bytes as usage.(all we have is 32/64 bits environment)
And I check my code , each summation of r,g,b , there is the maximum: 41(max gaussian kernel)_255(max rgb value)_25(each max summation number) = 261375. 
And the int range :  -2,147,483,648 to 2,147,483,647 ( unsigned int : 0 to 4,294,967,295)
There in the safe range.
Only expand version using output need to remind this.

**Comment by gnitnaw** [comment]
Let me explain you more:
Here is line 13 of gaussian.c

sum = global_src[(j-2)_info->width + i-2]_gaussian55[0] + global_src[(j-2)_info->width + i-1]_gaussian55[1]

If I understand well,
gaussian55: unsigned char : 0-255
global_src: unsigned char : 0-255

In the first part : global_src[(j-2)_info->width + i-2]_gaussian55[0],
since you didn't convert the type to uint16_t/uint32_t,
you will already have overflow because they are both unsigned char
(operation between unsigned char and unsigned char, there will be NO promotion of the type).
The overflow already happened BEFORE it is combined with sum.
You cannot expect that the compiler will treat like this:
(uint32_t)global_src[(j-2)_info->width + i-2]_gaussian55[0] .

For how to deal with overflow, in C it is UNDEFINED BEHAVIOUR.
It means you cannot expect what is going to happen.

**Comment by kevinbird61** [comment]
Thanks ! 
I got your point.
I'll fix them and update!

**Comment by gnitnaw** [comment]
Well, it's NOT enough to put only one explicit conversion...

The same, line 13 in gaussian.c:

sum = (int)global_src[(j-2)_info->width + i-2]_gaussian55[0] + global_src[(j-2)_info->width + i-1]_gaussian55[1]

Not only the first part, but also the others, they have the same problem....

You'd better to change the type of global_src to uint32_t or int32_t...

Ref: https://www.fefe.de/intof.html  Issue 3: Multiplication can overflow, too

PS: Maybe you will feel that unroll is not so fast anymore after correcting it well, but it is normal since you use uint8_t to do the calculation (and it's not correct since you have too much overflow). In your naive_gaussian_blur_5_original or naive_gaussian_blur_5, I see you use int (int32_t)

**Comment by kevinbird61** [comment]
Yes , after I add the cast on each summation of 2 elements , the execution times increased.
So you mean that the execution times increase as result of the execution result is correct now?

**Comment by kevinbird61** [comment]
I change the type of gaussian55 from "unsigned char " to "int" instead.
And find the time decrease to the same, still little longer than original.

**Comment by gnitnaw** [comment]
Yes. What you did in unroll is 8bit operation, which causes overflow.
The only way to avoid overflow is to use 16bit or 32bit operation, of course it is slower.
The improvement using unroll is usually "quite limited", I also felt strange when I saw your result.

**Comment by kevinbird61** [comment]
Thank for this useful concept!

**Comment by gnitnaw** [comment]
Have you already fixed this problem in your code ?

**Comment by kevinbird61** [comment]
Yes , I modify gaussian55 into "int". Make sure most of blur function work safe.
And cast the 1D gaussian blur each summation element to "float".

**Comment by gnitnaw** [comment]
OK. I see it.

**Comment by gnitnaw** [comment]
If unroll doesn't help significantly, you can simply remove it.

**Comment by kevinbird61** [comment]
Ok , I'll do that when we pack our program.
Thank a lot for providing so many useful concepts, and the time you spend on reviewing my code！

**Comment by gnitnaw** [comment]
Please complement your report first, we still have to improve other part.
