### ISSUE TITLE
Check the setting declarations of functions.

### ISSUE THREAD

**Issue by gnitnaw** [kevinbird61/Image-Processing#7]
I get lots of warnings : implicit declaration of function.

**Comment by kevinbird61** [comment]
Thank you !
I add the function declarations in main.c first ;
But I will change Makefile to link those header files with main.c , 
and remove those declarations in it.

**Comment by kevinbird61** [comment]
Now I have change for it !
You can pull it down and try it again!

**Comment by gnitnaw** [comment]
Thanks. Other comments I will put on your note.
