### ISSUE TITLE
The way you make the comments

### ISSUE THREAD

**Issue by gnitnaw** [kevinbird61/Image-Processing#8]
is not so good, for example:

  9 /*********************************************************/
 10 /*  Global variables declaration：                                             */
 11 /*  bmpHeader    ： BMP's header part
 12 /*  bmpInfo      ： BMP's file infomation
 13 /*  **BMPSaveData： BMP's data , which will be store into output
 14 /*  **BMPData    ： BMP's temperary data storage
 15 /*********************************************************/

If you put -Wall parameter to check all warnings, you will get:
main.c:12:1: warning: "/*" within comment [-Wcomment]
 /*  bmpInfo      ： BMP's file infomation
 ^
main.c:13:1: warning: "/*" within comment [-Wcomment]
 /*  **BMPSaveData： BMP's data , which will be store into output
 ^
main.c:14:1: warning: "/*" within comment [-Wcomment]
 /*  **BMPData    ： BMP's temperary data storage
 ^
main.c:15:1: warning: "/*" within comment [-Wcomment]
 /*********************************************************/
 ^

Normally we make comments like this
// This is a comment for one line

Or 
/* This is a comment */

But you do like this:
/* /* This is a comment  */

It's not easy for IDEs/editors to recognize your comments.

**Comment by kevinbird61** [comment]
OK ~ I have fix those comments in my code.
Thank for your report !
