### ISSUE TITLE
You have lots of malloc in main.c

### ISSUE THREAD

**Issue by gnitnaw** [kevinbird61/Image-Processing#9]
But no free....

**Comment by kevinbird61** [comment]
Fix the problem of missing free function!
Thank for your precious reminders!

**Comment by gnitnaw** [comment]
I'm afraid that you have to check again, especially in gaussian.c
You can use valgrind.

**Comment by kevinbird61** [comment]
I use valgrind and reduce the memory error from 50000 up to 4.
And will still searching why this 4 can't be fixed , which located at (pthread and pthread+sse version).
Thank for your suggestion!

**Comment by gnitnaw** [comment]
gaussian.c line 161.
You have to free it AFTER the thread is done (confirmed by pthread_join).
pt_gaussian_blur_5_tri : You forget to free threadInfo

Hint: each thread uses different tInfo[], and you free them after pthread_join, one-by-one.

**Comment by kevinbird61** [comment]
Thanks for your critical suggestion !
Now the program has no memory leak.(check via valgrind.)
